name: 'Continuous Integration'

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -e .
        pip install -r requirements.txt
        pip install -r requirements-test.txt
        
    - name: Create reports directory
      run: mkdir -p reports
        
    - name: Run model tests
      run: make model-test
      
    - name: Run API tests  
      run: make api-test
      
    - name: Upload test reports
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-reports
        path: reports/