name: 'Continuous Delivery'

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Verify successful CI
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" == "success" ]; then
            echo "CI passed successfully"
          else
            echo "CI must pass before deploying"
            exit 1
          fi
