name: 'Continuous Integration'

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
        pip install --upgrade anyio

        
    - name: Create reports directory
      run: mkdir -p reports
        
    - name: Run model tests
      run: make model-test

    - name: Run FastApi local  
      run: uvicorn challenge.api:app --host 0.0.0.0 --port 8000
      
    - name: Run API tests  
      run: make api-test
      
    - name: Upload test reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-reports
        path: reports/
        retention-days: 5